name: steady_calendar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.3
  supabase_flutter: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.otf
